### user create
POST localhost:8081/api/v1/user/111

### update
PUT localhost:8081/api/v1/user/111
Content-Type: application/json

{
  "role": "ADMIN"
}

### Get user by role
GET localhost:8081/api/v1/user/get-by-role/ADMIN

### get user by bot state
GET localhost:8081/api/v1/user/get-by-bot-state/START

